# Generated by Django 5.0.6 on 2024-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(max_length=255),
        ),
    ]
