# Generated by Django 5.0.6 on 2024-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0002_alter_student_roll_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
            ],
        ),
    ]
